language: php

dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
